export const ProjectDetailsText = {
  CidadaniaGV:
    "No aplicativo Cidadania GV, participei ativamente no desenvolvimento de grande parte das telas, tanto na área voltada para motoristas quanto na parte destinada aos passageiros. Realizei integrações com GraphQL e WebSocket para garantir comunicação em tempo real e eficiência no fluxo de dados. Além disso, no projeto GVBus, também atuei de forma significativa, desenvolvendo a maior parte das telas e funcionalidades do aplicativo. Trabalhei tanto na interface para passageiros quanto na área voltada aos motoristas, implementando integrações com o Google Maps e funcionalidades de geolocalização em tempo real, utilizando WebSocket para atualizações constantes de posição. Essas integrações proporcionaram uma experiência fluida e precisa para os usuários, garantindo que tanto motoristas quanto passageiros pudessem acompanhar as rotas e trajetos de forma eficaz e em tempo real.",
  PraticoRT:
    "No projeto Pratico RT, trabalhei arduamente focando em corrigir bugs e aprimorar a qualidade do código. Um dos principais desafios foi melhorar a estrutura geral, deixando o código mais limpo e organizado, o que facilitou a manutenção e futuras implementações. Além disso, dediquei bastante tempo ao sistema de gráficos, que havia sido implementado, mas apresentava problemas na exibição dos dados. Esses gráficos, que são parte essencial do aplicativo, exibem informações marítimas como temperatura do mar, direção em graus, e dados de boias, e estavam funcionando de maneira incorreta. Também foi necessário ajustar dados que haviam sido implementados de forma errada, garantindo que as informações marítimas fossem exibidas corretamente e de forma confiável para os usuários.",
  Sipolatti:
    "No projeto Sipolatti Vendedor, um aplicativo voltado para os vendedores das lojas físicas da Sipolatti, com foco em melhorar a experiência de venda e acesso às informações dos produtos. Trabalhei intensamente na integração de dados de produtos, garantindo que os vendedores pudessem acessar detalhes completos e atualizados sobre os itens disponíveis na loja. Além disso, implementei filtros avançados para facilitar a pesquisa e filtragem dos produtos, permitindo que os vendedores localizassem rapidamente o que seus clientes estavam buscando. Também fui responsável pela criação de telas intuitivas e de fácil navegação, onde os vendedores podiam visualizar imagens detalhadas dos produtos e todas as suas especificações. Na área de pagamento, implementei funcionalidades para geração de parcelas, proporcionando uma maneira fácil de calcular e visualizar as opções de pagamento. Esse trabalho incluiu a exibição de imagens e informações de produtos variados, de forma clara e organizada, auxiliando os vendedores no atendimento ao cliente de maneira eficiente e ágil.  Foi um projeto desafiador e gratificante, onde pude colaborar com diferentes aspectos do desenvolvimento do aplicativo, desde a integração de dados até a melhoria da usabilidade para os vendedores nas lojas.",
  DogPlan:
    "Neste projeto, contribui para o desenvolvimento de um aplicativo de plano de saúde para pets, focando na criação de uma experiência de usuário intuitiva e funcional. Desde o início, nosso objetivo era criar um app bem estruturado, que atendesse às necessidades dos usuários e facilitasse a gestão da saúde de seus animais de estimação. Iniciei o projeto com a criação de várias telas essenciais, permitindo que os usuários visualizem informações relevantes sobre seus pets e acessem funcionalidades principais, como agendamentos e histórico de consultas. Também contribui para a criação de uma tela de login segura, onde os usuários podem se autenticar de forma simples e eficiente, com validação de dados e manipulação de estados para garantir uma experiência fluida. Criei formulários para cadastro de pets e agendamentos de consultas, projetados com validação em tempo real. Além das telas mencionadas, implementei diversas funcionalidades, como o cadastro de pets, onde os usuários podem inserir informações como nome, raça, idade e histórico médico, proporcionando um gerenciamento mais eficiente da saúde dos animais. Também participei na integração um sistema de agendamento que permite marcar consultas com veterinários, facilitando a organização e o acompanhamento da saúde dos pets. O desenvolvimento deste aplicativo foi um projeto desafiador e gratificante, e, através de uma abordagem focada na experiência do usuário e no uso de tecnologias modernas, conseguimos criar um aplicativo robusto que atende às necessidades dos donos de pets.",
  MedSempre:
    "No projeto MedSempre, um aplicativo voltado para planos de saúde para pessoas, contribui significativamente para a criação de telas e integrações que tornam a experiência do usuário mais eficiente e acessível. O MedSempre foi desenvolvido com o objetivo de facilitar a gestão da saúde, permitindo que os usuários tenham acesso rápido a informações sobre seus planos, agendamentos de consultas e histórico médico.",
  Vapt: "No projeto Vapt, uma plataforma desenvolvida para aproximar colaboradores, clientes, fornecedores e parceiros, contribui ativamente para a criação de telas e integrações que aprimoram a comunicação e a interação entre os usuários. O Vapt tem como missão facilitar o acesso a notícias, campanhas e ferramentas, oferecendo uma experiência intuitiva e eficiente.",
  "DBL - Precificação e Orçamentos":
    "Desenvolvi o app DBL – Precificação e Orçamentos do zero até a publicação nas lojas, utilizando React Native. Ele foi criado para ajudar artesãos a precificar seus produtos de forma justa e profissional, além de oferecer ferramentas para organização de clientes e envio de orçamentos personalizados. O app permite cadastrar materiais, calcular automaticamente o valor ideal de venda com base no tempo e margem de lucro, registrar clientes e gerar orçamentos com praticidade. Disponível para Android e iOS, com uma interface simples, acessível e eficiente.",
};
