name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack and activate Yarn 4.5.3
        run: |
          corepack enable
          corepack prepare yarn@4.5.3 --activate
          yarn --version

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Export static site
        run: yarn next export

      - name: Upload artifact (plano B)
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
